from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import ActionableTask
from .serializers import ActionableTaskSerializer, AgentExecuteInputSerializer
from .graph import execute_agent_workflow


class AgentExecuteView(APIView):
    """
    Blueprint: POST /api/v1/agent/execute/
    Executes an autonomous LangGraph agent loop with tools (Milvus search, Task creation, n8n webhook).
    """
    def post(self, request):
        serializer = AgentExecuteInputSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        prompt = serializer.validated_data['prompt']

        try:
            result = execute_agent_workflow(prompt)
            return Response({
                "prompt": prompt,
                "response": result["output"],
                "steps_taken": result["total_messages"]
            }, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({
                "error": f"Agent execution failed: {str(e)}"
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class TaskListView(generics.ListAPIView):
    """
    Blueprint: GET /api/v1/tasks/
    Lists all actionable items generated by the AI agent.
    """
    queryset = ActionableTask.objects.all()
    serializer_class = ActionableTaskSerializer
    